version: 2
updates:
  - package-ecosystem: npm
    directory: '/'
    schedule:
      interval: daily
    groups:
      dependencies:
        patterns:
          - '*'
    assignees:
      - koki-sato
    allow:
      - dependency-type: direct
