# JavaScript CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2

jobs:
  test:
    docker:
      - image: circleci/node:10.16
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies-
      - run: yarn install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - run: yarn build
      - run: yarn test
  deploy:
    docker:
      - image: circleci/node:10.16
    steps:
      - checkout
      - run: yarn install
      - run: git config user.name $GITHUB_NAME
      - run: git config user.email $GITHUB_EMAIL
      - run: yarn run deploy

workflows:
  version: 2
  test-and-deploy:
    jobs:
      - test:
          filters:
            branches:
              ignore: master
      - deploy:
          requires:
            - test
          filters:
            branches:
              only: develop
