version: 1

update_configs:
  - package_manager: javascript
    directory: /
    update_schedule: live
    default_assignees:
      - koki-sato
    allowed_updates:
      - match:
          dependency_type: direct
    automerged_updates:
      - match:
          dependency_type: all
          update_type: semver:minor
