name: CD

on:
  push:
    branches: [develop]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v1
      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 10
      - run: yarn install
      - run: git config user.name $MY_GITHUB_NAME
        env:
          MY_GITHUB_NAME: ${{ secrets.MY_GITHUB_NAME }}
      - run: git config user.email $MY_GITHUB_EMAIL
        env:
          MY_GITHUB_EMAIL: ${{ secrets.MY_GITHUB_EMAIL }}
      - run: yarn run deploy
